logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:mariadb://locahost:3306/oauth2db
    username: root
    password: jvman19
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
